controllers/AdminController.php
<?php namespace app\controllers;

use app\models\Authors;
use app\models\AuthorsForBooks;
use app\models\Books;
use app\models\BooksSearch;
use app\models\Categories;
use app\models\CategoriesForBooks;
use app\models\Feedback;
use app\models\Rules;
use app\models\Statuses;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Response;

class AdminController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id=='login')
                $this->layout = 'login';
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param string $rule
     * @return string|\yii\web\Response
     */
    public function actionRule(string $rule)
    {
        $model = Rules::find()->where(['name' => $rule])->one();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('changeRule' . $rule);
            return $this->refresh();
        }
        return $this->render('rule', [
            'model' => $model,
        ]);
    }

    public function actionFeedback() : string
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Feedback::find()
        ]);
        return $this->render('feedback', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionBooks() : string
    {
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 20, true);
        return $this->render('../site/books', [
            'fromAdmin' => true,
            'category' => '',
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'statuses' => ['' => ''] + ArrayHelper::map(Statuses::find()->orderBy('id')->all(), 'id', 'name'),
            'authorSearch' => isset(Yii::$app->request->queryParams['author_name']) ?
                Yii::$app->request->queryParams['author_name'] : ''
        ]);
    }

    public function actionModifyBook(int $id) : string
    {
        $book = Books::find()
            ->with('status')
            ->with('authorForBook')
            ->with('categoryForBook')
            ->where(['id' => $id ])->one();
        return $this->render('view', [
            'model' => $book,
        ]);
    }

    public function actionAddBook() : string
    {
        if (Yii::$app->request->isPost) {
            $model = new Books();
            $post = Yii::$app->request->post();
            $model->load($post);
            $modelFromDB = Books::find()->where(['title' => $model->title])->one();
            if ($modelFromDB) {
                return $this->render('view', [
                    'message' => true,
                    'model' => $modelFromDB,
                ]);
            } else {
                $model->updatePicture($_FILES['Books']['name']['picture']);
                if (isset($post['status']) && $post['status'] !== "") {
                    $model = Statuses::setStatus($model, $post['status']);
                }
                $model->save();
                $modelId = $model->id;
                $categories = isset($post['categories']) && $post['categories'] !== "" ? $post['categories'] : Categories::DEFAULT_CATEGORY;
                Categories::setCategory($modelId, $categories);

                if (isset($post['authors']) && $post['authors'] !== "") {
                    Authors::setAuthors($modelId, $post['authors']);
                }
                $book = Books::find()
                    ->with('status')
                    ->with('authorForBook')
                    ->with('categoryForBook')
                    ->where(['id' => $modelId])->one();
                return $this->render('view', [
                    'model' => $book,
                ]);
            }
        }

        return $this->render('create', [
            'model' => new Books(),
        ]);
    }

    public function actionDeleteBook(int $id) : Response
    {
        CategoriesForBooks::deleteAll(['book_id' => $id]);
        AuthorsForBooks::deleteAll(['book_id' => $id]);
        Books::find()->where(['id' => $id])->one()->delete();

        return $this->redirect(['/admin/books']);
    }

    public function actionUpdateBook(int $id) : string
    {
        $book = Books::find()
            ->with('status')
            ->with('authorForBook')
            ->with('categoryForBook')
            ->where(['id' => $id])->one();
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            if (isset($post['Books']['picture']) && $post['Books']['picture'] === '') {
                unset($post['Books']['picture']);
            }
            $book->load($post);
            if ($_FILES['Books']['name']['picture'] !== '') {
                $book->updatePicture($_FILES['Books']['name']['picture']);
            }
            if (isset($post['status']) && $post['status'] !== "") {
                $book = Statuses::setStatus($book, $post['status']);
            }
            $book->save();
            $categories = isset($post['categories']) && $post['categories'] !== "" ? $post['categories'] : Categories::DEFAULT_CATEGORY;
            Categories::setCategory($id, $categories, true);
            if (isset($post['authors']) && $post['authors'] !== "") {
                Authors::setAuthors($id, $post['authors'], true);
            }
            return $this->render('view', [
                'model' => Books::find()->with('status')->with('authorForBook')->with('categoryForBook')->where(['id' => $id])->one(),
            ]);
        }

        return $this->render('update', [
            'model' => $book,
        ]);
    }
}

controllers/SiteController.php
<?php namespace app\controllers;

use app\models\Books;
use app\models\BooksSearch;
use app\models\Categories;
use app\models\CategoriesForBooks;
use app\models\Rules;
use app\models\Statuses;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Response;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id=='login')
                $this->layout = 'login';
            return true;
        } else {
            return false;
        }
    }

    public function actionIndex() : string
    {
        $categories = Categories::find()->all();
        return $this->render('index', ['categories' => $categories]);
    }

    public function actionBooks(int $category) : string
    {
        $categoryFromDB = Categories::find()->where(['id' => $category])->one();
        $pageSize = Rules::getValue(Rules::COUNT_RULE);
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $pageSize);
        return $this->render('books', [
            'fromAdmin' => false,
            'category' => $categoryFromDB,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'statuses' => ['' => ''] + ArrayHelper::map(Statuses::find()->orderBy('id')->all(), 'id', 'name'),
            'authorSearch' => isset(Yii::$app->request->queryParams['author_name']) ?
                Yii::$app->request->queryParams['author_name'] : ''
        ]);
    }

    public function actionBook(int $id, int $category) : string
    {
        $book = Books::find()
            ->with('categoryForBook')
            ->where(['id' => $id ])->one();
        return $this->render('book', [
            'model' => $book,
            'category' => Categories::find()->where(['id' => $category])->one(),
            'otherBooks' => Books::find()
                ->leftJoin(CategoriesForBooks::tableName(), Books::tableName() . '.id = ' . CategoriesForBooks::tableName() . '.book_id')
                ->where(['category_id' => $category])
                ->andWhere(['!=', Books::tableName() . '.id', $id])
                ->all()
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() : Response
    {
        Yii::$app->user->logout();
        return $this->redirect(Yii::$app->user->loginUrl);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        $email = Rules::getValue(Rules::EMAIL_RULE);
        if ($model->load(Yii::$app->request->post()) && $model->contact($email)) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
}

views/admin/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $model app\models\Books
 * @var $form yii\widgets\ActiveForm
 */

$update = (isset($update)) ? $update : false;
$author = [];
foreach ($model->authorForBook as $value) {
    $author[] = $value->name;
}
$author = implode(', ', $author);
$category = [];
foreach ($model->categoryForBook as $value) {
    $category[] = $value->name;
}
$category = implode(', ', $category);
?>

<div class="books-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'isbn')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pages')->input('number', ['max' => 9999, 'min' => 0]) ?>

    <?= $form->field($model, 'publish_date')->input('date') ?>

    <?= $model->picture ? '<p class = "control-label"><b>Текущая обложка: </b></p>
    <img src = "' . '/images/' . $model->picture . '" alt = "' . $model->title . '">' : ''; ?>
    <?= $form->field($model, 'picture')->fileInput(['class' => 'url-file-input'])->label('Выберете обложку: ') ?>

    <?= $form->field($model, 'short_description')->textArea(['maxlength' => true]) ?>

    <?= $form->field($model, 'long_description')->textArea(['maxlength' => true]) ?>

    <?= Html::label('Статус', 'status', ['class' => 'control-label']) ?>
    <?= Html::textInput('status', $update ? ($model->status->name ?? '') : '', ['class' => 'form-control']) ?>

    <?= Html::label('Категории', 'categories', ['class' => 'control-label']) ?>
    <?= Html::textInput('categories', $category, ['class' => 'form-control']) ?>

    <?= Html::label('Авторы', 'authors', ['class' => 'control-label']) ?>
    <?= Html::textInput('authors', $author, ['class' => 'form-control']) ?>
    <p class="control-label">При вводе <b>нескольких Категорий или Авторов</b> для книги указывайте значения <b>через ","</b> !</p>

    <div class="form-group">
        <?= Html::submitButton('Save', ['id' => 'user-save', 'class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/admin/create.php
<?php

use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $model app\models\Books
 */

$this->title = 'Создание книги';
$this->params['breadcrumbs'][] = ['label' => 'Все книги', 'url' => ['/admin/books']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/admin/feedback.php
<?php

use yii\data\ActiveDataProvider;
use yii\grid\GridView;

/**
 * @var $this yii\web\View
 * @var $dataProvider ActiveDataProvider
 */

$this->title = 'Просмотр заявок с формы обратной связи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">
    <h1><?= $this->title ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
    ]); ?>
</div>

views/admin/rule.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Rules;

/**
 * @var $this yii\web\View
 * @var $form ActiveForm
 * @var $model Rules
 */

$this->title = 'Настройки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1>Изменение параметра <?= $model->name ?></h1>

    <?php if (Yii::$app->session->hasFlash('changeRule' . $model->name)): ?>
        <div class="alert alert-success">
            Изменение данного параметра прошло успешно.
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'rule-form']); ?>
            <?= $model->name === Rules::URL_RULE ?
                $form->field($model, 'value')->input('url') :
                ($model->name === Rules::EMAIL_RULE ? $form->field($model, 'value')->input('email') :
                    $form->field($model, 'value')->input('number'))
            ?>
            <div class="form-group">
                <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/admin/update.php
<?php

use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $model app\models\Books
 */

$this->title = 'Обновить книгу ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Все книги', 'url' => ['/admin/books']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-create">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'update' => true,
        'model' => $model,
    ]) ?>
</div>

views/admin/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use app\models\Authors;

/**
 * @var $this yii\web\View
 * @var $model app\models\Books
 * @var $authors Authors
 */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Все книги', 'url' => ['admin/books']];
$this->params['breadcrumbs'][] = $this->title;

$message = isset($message) ? $message : false;
?>

<div class="books-view">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php if($message) : ?>
        <div class="alert alert-success">
            Книга с таким названием уже существует!
        </div>
    <?php endif; ?>
    <p>
        <?= Html::a('Изменить', ['admin/update-book', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['admin/delete-book', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить данную книгу?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'isbn',
            'pages',
            'publish_date',
            'short_description',
            'long_description',
            [
                'label' => 'Обложка',
                'value' => function ($model) {
                    return $model->picture ? '<img src = "' . '/images/' . $model->picture . '" alt = "' . $model->title . '">' : '';
                },
                'format' => 'raw'
            ],
            [
                'label' => 'Статус',
                'value' => function ($data) {
                    return $data->status->name ?? '';
                },
                'format' => 'raw'
            ],
            [
                'label' => 'Авторы',
                'value' => function ($data) {
                    $author = [];
                    foreach ($data->authorForBook as $value) {
                        $author[] = $value->name;
                    }
                    return implode(', ', $author);
                },
                'format' => 'raw'
            ],
            [
                'label' => 'Категории',
                'value' => function ($model) {
                    $answer = '';
                    foreach ($model->categoryForBook as $category) {
                        $answer .= '<a href = "' . Url::to(['site/books', 'category' => $category->id]) . '">' . $category->name . '</a><br>';
                    }
                    return $answer;
                },
                'format' => 'raw'
            ],
        ],
    ]) ?>
</div>