controllers/AdminController.php
<?php namespace app\controllers;

use app\models\Authors;
use app\models\AuthorsForBooks;
use app\models\Books;
use app\models\BooksSearch;
use app\models\Categories;
use app\models\CategoriesForBooks;
use app\models\Feedback;
use app\models\Rules;
use app\models\Statuses;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Response;

class AdminController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id=='login')
                $this->layout = 'login';
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param string $rule
     * @return string|\yii\web\Response
     */
    public function actionRule(string $rule)
    {
        $model = Rules::find()->where(['name' => $rule])->one();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('changeRule' . $rule);
            return $this->refresh();
        }
        return $this->render('rule', [
            'model' => $model,
        ]);
    }

    public function actionFeedback() : string
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Feedback::find()
        ]);
        return $this->render('feedback', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionBooks() : string
    {
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 20, true);
        return $this->render('../site/books', [
            'fromAdmin' => true,
            'category' => '',
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'statuses' => ['' => ''] + ArrayHelper::map(Statuses::find()->orderBy('id')->all(), 'id', 'name'),
            'authorSearch' => isset(Yii::$app->request->queryParams['author_name']) ?
                Yii::$app->request->queryParams['author_name'] : ''
        ]);
    }

    public function actionModifyBook(int $id) : string
    {
        $book = Books::find()
            ->with('status')
            ->with('authorForBook')
            ->with('categoryForBook')
            ->where(['id' => $id ])->one();
        return $this->render('view', [
            'model' => $book,
        ]);
    }

    public function actionAddBook() : string
    {
        if (Yii::$app->request->isPost) {
            $model = new Books();
            $post = Yii::$app->request->post();
            $model->load($post);
            $modelFromDB = Books::find()->where(['title' => $model->title])->one();
            if ($modelFromDB) {
                return $this->render('view', [
                    'message' => true,
                    'model' => $modelFromDB,
                ]);
            } else {
                $model->updatePicture($_FILES['Books']['name']['picture']);
                if (isset($post['status']) && $post['status'] !== "") {
                    $model = Statuses::setStatus($model, $post['status']);
                }
                $model->save();
                $modelId = $model->id;
                $categories = isset($post['categories']) && $post['categories'] !== "" ? $post['categories'] : Categories::DEFAULT_CATEGORY;
                Categories::setCategory($modelId, $categories);

                if (isset($post['authors']) && $post['authors'] !== "") {
                    Authors::setAuthors($modelId, $post['authors']);
                }
                $book = Books::find()
                    ->with('status')
                    ->with('authorForBook')
                    ->with('categoryForBook')
                    ->where(['id' => $modelId])->one();
                return $this->render('view', [
                    'model' => $book,
                ]);
            }
        }

        return $this->render('create', [
            'model' => new Books(),
        ]);
    }

    public function actionDeleteBook(int $id) : Response
    {
        CategoriesForBooks::deleteAll(['book_id' => $id]);
        AuthorsForBooks::deleteAll(['book_id' => $id]);
        Books::find()->where(['id' => $id])->one()->delete();

        return $this->redirect(['/admin/books']);
    }

    public function actionUpdateBook(int $id) : string
    {
        $book = Books::find()
            ->with('status')
            ->with('authorForBook')
            ->with('categoryForBook')
            ->where(['id' => $id])->one();
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            if (isset($post['Books']['picture']) && $post['Books']['picture'] === '') {
                unset($post['Books']['picture']);
            }
            $book->load($post);
            if ($_FILES['Books']['name']['picture'] !== '') {
                $book->updatePicture($_FILES['Books']['name']['picture']);
            }
            if (isset($post['status']) && $post['status'] !== "") {
                $book = Statuses::setStatus($book, $post['status']);
            }
            $book->save();
            $categories = isset($post['categories']) && $post['categories'] !== "" ? $post['categories'] : Categories::DEFAULT_CATEGORY;
            Categories::setCategory($id, $categories, true);
            if (isset($post['authors']) && $post['authors'] !== "") {
                Authors::setAuthors($id, $post['authors'], true);
            }
            return $this->render('view', [
                'model' => Books::find()->with('status')->with('authorForBook')->with('categoryForBook')->where(['id' => $id])->one(),
            ]);
        }

        return $this->render('update', [
            'model' => $book,
        ]);
    }
}

views/layouts/content.php
<?php

use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

/**
 * @var $content string
*/
?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo Html::encode($this->title);
                } else {
                    echo Inflector::camel2words(
                        Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>

views/layouts/header.php
<?php

use yii\helpers\Html;

?>

<header class="main-header">
    <?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->params['name'] . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
    </nav>
</header>

views/layouts/left.php
<?php

use app\models\Rules;
use dmstr\widgets\Menu;

?>

<aside class="main-sidebar">
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist') ?>/img/user2-160x160.jpg"
                     class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->user->isGuest ? 'Guest' : Yii::$app->user->identity->username; ?></p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <?= Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget' => 'tree'],
                'items' => [
                    ['label' => '', 'options' => ['class' => 'header']],
                    [
                        'label' => 'Изменение книг',
                        'icon' => 'share',
                        'url' => ['admin/books']
                    ],
                    [
                        'label' => 'Настройки',
                        'icon' => 'share',
                        'url' => '#',
                        'items' => [
                            ['label' => 'На странице книг', 'icon' => 'file-code-o', 'url' => ['admin/rule', 'rule' => Rules::COUNT_RULE],],
                            ['label' => 'Url для парсинга книг', 'icon' => 'file-code-o', 'url' => ['admin/rule', 'rule' => Rules::URL_RULE],],
                            ['label' => 'Email получателя писем', 'icon' => 'file-code-o', 'url' => ['admin/rule', 'rule' => Rules::EMAIL_RULE],],
                            ['label' => 'Просмотр заявок', 'icon' => 'file-code-o', 'url' => ['admin/feedback'],],
                        ],
                    ],
                    ['label' => 'Обратная связь', 'icon' => 'file-code-o', 'url' => ['/contact'],],
                    Yii::$app->user->isGuest ? (
                            ['label' => 'Войти', 'url' => ['/site/login']]
                    ) : (
                            ['label' => 'Выйти', 'url' => ['/site/logout']]
                    )
                ],
            ]
        ) ?>
    </section>
</aside>

views/layouts/login.php
<?php

/* @var $content string */

echo $this->render(
    'main-login',
    ['content' => $content]
);

views/layouts/main-login.php
<?php

use yii\helpers\Html;
use dmstr\web\AdminLteAsset;
use yii\web\View;

/**
 * @var $this View
 * @var $content string
 */

AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

use yii\helpers\Html;
use app\assets\AppAsset;
use dmstr\web\AdminLteAsset;

/**
 * @var $this \yii\web\View
 * @var $content string
 */

AppAsset::register($this);
AdminLteAsset::register($this);
$directoryAsset = Yii::$app->assetManager->getPublishedUrl('/views/layouts/');
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>