controllers/AdminController.php
<?php namespace app\controllers;

use app\models\Authors;
use app\models\AuthorsForBooks;
use app\models\Books;
use app\models\BooksSearch;
use app\models\Categories;
use app\models\CategoriesForBooks;
use app\models\Feedback;
use app\models\Rules;
use app\models\Statuses;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Response;

class AdminController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id=='login')
                $this->layout = 'login';
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param string $rule
     * @return string|\yii\web\Response
     */
    public function actionRule(string $rule)
    {
        $model = Rules::find()->where(['name' => $rule])->one();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('changeRule' . $rule);
            return $this->refresh();
        }
        return $this->render('rule', [
            'model' => $model,
        ]);
    }

    public function actionFeedback() : string
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Feedback::find()
        ]);
        return $this->render('feedback', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionBooks() : string
    {
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 20, true);
        return $this->render('../site/books', [
            'fromAdmin' => true,
            'category' => '',
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'statuses' => ['' => ''] + ArrayHelper::map(Statuses::find()->orderBy('id')->all(), 'id', 'name'),
            'authorSearch' => isset(Yii::$app->request->queryParams['author_name']) ?
                Yii::$app->request->queryParams['author_name'] : ''
        ]);
    }

    public function actionModifyBook(int $id) : string
    {
        $book = Books::find()
            ->with('status')
            ->with('authorForBook')
            ->with('categoryForBook')
            ->where(['id' => $id ])->one();
        return $this->render('view', [
            'model' => $book,
        ]);
    }

    public function actionAddBook() : string
    {
        if (Yii::$app->request->isPost) {
            $model = new Books();
            $post = Yii::$app->request->post();
            $model->load($post);
            $modelFromDB = Books::find()->where(['title' => $model->title])->one();
            if ($modelFromDB) {
                return $this->render('view', [
                    'message' => true,
                    'model' => $modelFromDB,
                ]);
            } else {
                $model->updatePicture($_FILES['Books']['name']['picture']);
                if (isset($post['status']) && $post['status'] !== "") {
                    $model = Statuses::setStatus($model, $post['status']);
                }
                $model->save();
                $modelId = $model->id;
                $categories = isset($post['categories']) && $post['categories'] !== "" ? $post['categories'] : Categories::DEFAULT_CATEGORY;
                Categories::setCategory($modelId, $categories);

                if (isset($post['authors']) && $post['authors'] !== "") {
                    Authors::setAuthors($modelId, $post['authors']);
                }
                $book = Books::find()
                    ->with('status')
                    ->with('authorForBook')
                    ->with('categoryForBook')
                    ->where(['id' => $modelId])->one();
                return $this->render('view', [
                    'model' => $book,
                ]);
            }
        }

        return $this->render('create', [
            'model' => new Books(),
        ]);
    }

    public function actionDeleteBook(int $id) : Response
    {
        CategoriesForBooks::deleteAll(['book_id' => $id]);
        AuthorsForBooks::deleteAll(['book_id' => $id]);
        Books::find()->where(['id' => $id])->one()->delete();

        return $this->redirect(['/admin/books']);
    }

    public function actionUpdateBook(int $id) : string
    {
        $book = Books::find()
            ->with('status')
            ->with('authorForBook')
            ->with('categoryForBook')
            ->where(['id' => $id])->one();
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            if (isset($post['Books']['picture']) && $post['Books']['picture'] === '') {
                unset($post['Books']['picture']);
            }
            $book->load($post);
            if ($_FILES['Books']['name']['picture'] !== '') {
                $book->updatePicture($_FILES['Books']['name']['picture']);
            }
            if (isset($post['status']) && $post['status'] !== "") {
                $book = Statuses::setStatus($book, $post['status']);
            }
            $book->save();
            $categories = isset($post['categories']) && $post['categories'] !== "" ? $post['categories'] : Categories::DEFAULT_CATEGORY;
            Categories::setCategory($id, $categories, true);
            if (isset($post['authors']) && $post['authors'] !== "") {
                Authors::setAuthors($id, $post['authors'], true);
            }
            return $this->render('view', [
                'model' => Books::find()->with('status')->with('authorForBook')->with('categoryForBook')->where(['id' => $id])->one(),
            ]);
        }

        return $this->render('update', [
            'model' => $book,
        ]);
    }
}

controllers/SiteController.php
<?php namespace app\controllers;

use app\models\Books;
use app\models\BooksSearch;
use app\models\Categories;
use app\models\CategoriesForBooks;
use app\models\Rules;
use app\models\Statuses;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Response;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id=='login')
                $this->layout = 'login';
            return true;
        } else {
            return false;
        }
    }

    public function actionIndex() : string
    {
        $categories = Categories::find()->all();
        return $this->render('index', ['categories' => $categories]);
    }

    public function actionBooks(int $category) : string
    {
        $categoryFromDB = Categories::find()->where(['id' => $category])->one();
        $pageSize = Rules::getValue(Rules::COUNT_RULE);
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $pageSize);
        return $this->render('books', [
            'fromAdmin' => false,
            'category' => $categoryFromDB,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'statuses' => ['' => ''] + ArrayHelper::map(Statuses::find()->orderBy('id')->all(), 'id', 'name'),
            'authorSearch' => isset(Yii::$app->request->queryParams['author_name']) ?
                Yii::$app->request->queryParams['author_name'] : ''
        ]);
    }

    public function actionBook(int $id, int $category) : string
    {
        $book = Books::find()
            ->with('categoryForBook')
            ->where(['id' => $id ])->one();
        return $this->render('book', [
            'model' => $book,
            'category' => Categories::find()->where(['id' => $category])->one(),
            'otherBooks' => Books::find()
                ->leftJoin(CategoriesForBooks::tableName(), Books::tableName() . '.id = ' . CategoriesForBooks::tableName() . '.book_id')
                ->where(['category_id' => $category])
                ->andWhere(['!=', Books::tableName() . '.id', $id])
                ->all()
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() : Response
    {
        Yii::$app->user->logout();
        return $this->redirect(Yii::$app->user->loginUrl);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        $email = Rules::getValue(Rules::EMAIL_RULE);
        if ($model->load(Yii::$app->request->post()) && $model->contact($email)) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/book.php
<?php

use app\models\Categories;
use app\models\Books;
use yii\helpers\Url;
use yii\widgets\DetailView;

/**
 * @var $this yii\web\View
 * @var $model Books
 * @var $category Categories
 * @var $otherBooks Books
 */

$this->title = 'Книга ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => $category->name, 'url' => Url::to(['site/books', 'category' => $category->id])];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-index">
    <h1><?= $this->title ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'title',
            'isbn',
            [
                'label' => 'Обложка',
                'value' => function ($model) {
                    return $model->picture ? '<img src = "' . '/images/' . $model->picture . '" alt = "' . $model->title . '">' : '';
                },
                'format' => 'raw'
            ],
            [
                'label' => 'Категории',
                'value' => function ($model) {
                    $answer = '';
                    foreach ($model->categoryForBook as $category) {
                        $answer .= '<a href = "' . Url::to(['site/books', 'category' => $category->id]) . '">' . $category->name . '</a><br>';
                    }
                    return $answer;
                },
                'format' => 'raw'
            ],
            [
                'label' => 'Книги из текущей категории',
                'value' => function () use ($otherBooks, $category) {
                    $answer = '';
                    foreach ($otherBooks as $book) {
                        $answer .= '<a href = "' . Url::to(['site/book', 'id' => $book->id, 'category' => $category->id]) . '">' . $book->title . '</a><br>';
                    }
                    return $answer;
                },
                'format' => 'raw'
            ],
        ],
    ]); ?>
</div>

views/site/books.php
<?php

use app\models\Categories;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\helpers\Html;
use app\models\BooksSearch;
use yii\data\ActiveDataProvider;

/* @var $this yii\web\View
 * @var $category Categories
 * @var $searchModel BooksSearch
 * @var $dataProvider ActiveDataProvider
 * @var $statuses array
 * @var $authorSearch string
 * @var $fromAdmin bool
 */

$this->title = $fromAdmin ? 'Все книги' : 'Книги из категории ' . $category->name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">
    <h1><?= $this->title ?></h1>

    <div>
        <?php if($fromAdmin) : ?>
        <a href="<?= Url::to(['/admin/add-book'])?>" class="btn btn-success">Добавить книгу</a>
        <?php endif; ?>
    </div>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'title',
            [
                'attribute' => 'status',
                'label' => 'Статус',
                'format' => 'raw',
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status_id',
                    $statuses,
                    ['class' => 'form-control']
                ),
                'value' => function ($data) {
                    return $data->status->name ?? '';
                },
            ],
            [
                'attribute' => 'author_name',
                'label' => 'Автор',
                'filter' => Html::input('string', 'author_name', $authorSearch, ['class' => 'form-control']),
                'value' => function ($data) {
                    $author = [];
                    foreach ($data->authorForBook as $value) {
                        $author[] = $value->name;
                    }
                    return implode(', ', $author);
                },
                'format' => 'raw',
            ],
            [
                'label' => 'Перейти',
                'value' => function ($data) use ($category, $fromAdmin) {
                    return '<a href = "' . ($fromAdmin ? Url::to(['admin/modify-book', 'id' => $data->id]) :
                        Url::to(['site/book', 'id' => $data->id, 'category' => $category->id]))
                        . '">==></a>';
                },
                'format' => 'raw',
            ],
        ],
    ]); ?>
</div>

views/site/contact.php
<?php

use himiklab\yii2\recaptcha\ReCaptcha2;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\MaskedInput;

/**
 * @var $this yii\web\View
 * @var $form yii\bootstrap\ActiveForm
 * @var $model app\models\ContactForm
 */

$this->title = 'Обратная связь';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>
        <div class="alert alert-success">
            Спасибо за обратную связь.
        </div>
    <?php else: ?>
        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'message')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'phone')
                    ->widget(MaskedInput::class,
                        ['mask' => '+7 (999) 999-99-99'])
                    ->textInput(['placeholder' => '+7 (999) 999-99-99', 'class' => '']);
                ?>

                <?= $form->field($model, 'verifyCode')->widget(
                    ReCaptcha2::class,
                    ['siteKey' => '6LcHifEZAAAAAFhc5LOMrLLAby5WzCXpzfIQwKCC']
                ) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

views/site/index.php
<?php

use app\models\Categories;
use yii\helpers\Url;

/* @var $this yii\web\View
 * @var $categories Categories[]
 */

$this->title = 'Главная страница';
?>
<div class="site-index">
    <h1>Категории книг</h1>
    <div class="body-content">
        <?php foreach ($categories as $category) : ?>
        <div><a href="<?= Url::to(['site/books', 'category' => $category->id]) ?>"><b><?= $category->name ?></b></a></div>
        <?php endforeach; ?>
    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\LoginForm;
use yii\web\View;

/**
 * @var $this View
 * @var $form ActiveForm
 * @var $model LoginForm
 */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-box-body">
        <p class="login-box-msg">Войти на сайт</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Sign in', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>

        <div class="row">
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>
        <?php ActiveForm::end(); ?>
    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->